IP_BLOCKED_PAGE_ENDPOINT = "ip_blocked"
IP_BLOCKED_PING_ENDPOINT = "ip_blocked_ping"
IP_BLOCKED_STATIC_ENDPOINT = "ip_blocked.static"
IP_BLOCKED_ENDPOINTS = frozenset({IP_BLOCKED_PAGE_ENDPOINT, IP_BLOCKED_PING_ENDPOINT})
IP_BLOCKED_ACCESS_ENDPOINTS = IP_BLOCKED_ENDPOINTS | frozenset({IP_BLOCKED_STATIC_ENDPOINT})
