[Interface]
PrivateKey = ${CLIENT_PRIVATE_KEY}
Address = ${CLIENT_IP}/${WIREGUARD_CLIENT_PREFIX}${WIREGUARD_CLIENT_IPV6}
DNS = 10.29.8.1${WIREGUARD_TABLE}

[Peer]
PublicKey = ${PUBLIC_KEY}
PresharedKey = ${CLIENT_PRESHARED_KEY}
Endpoint = ${SERVER_HOST}:51443
AllowedIPs = ${WIREGUARD_ALLOWED_IPS}
PersistentKeepalive = 15
