[Interface]
PrivateKey = ${CLIENT_PRIVATE_KEY}
Address = ${CLIENT_IP}/32${WIREGUARD_CLIENT_IPV6}
DNS = 1.1.1.1, 1.0.0.1

[Peer]
PublicKey = ${PUBLIC_KEY}
PresharedKey = ${CLIENT_PRESHARED_KEY}
Endpoint = ${WIREGUARD_SERVER_HOST}:51080
AllowedIPs = 0.0.0.0/0${WIREGUARD_IPV6_ROUTES}
PersistentKeepalive = 15
